- name: itemls
  hosts: localhost
  become: true
  connection: local
  tasks:
   - name: install LEMP
     apt:
      name: "{{item}}"
      state: present
     with_items:
       - nginx
       - php
       - php8.3-fpm
       - mariadb-server
   - name: Start LEMP
     service:
      name: "{{item}}"
      state: started
     with_items:
        - nginx
        - php8.3-fpm
        - mariadb
   - name: Retart LEMP
     service:
      name: "{{item}}"
      state: restarted
     with_items:
        - nginx
        - php8.3-fpm
        - mariadb
