- name: stopnginxandstartappache2
  hosts: localhost
  become: true
  connection: local
  tasks:
   - name: stop nginx
     service:
      name: nginx
      state: stopped
   - name: install apache2
     apt:
      name: apache2
      state: present
   - name: start apache2 service
     service:
      name: apache2
      state: started
