- name: learning inventry
  hosts: all
  become: true
  tasks:
    - name: update dnf
      shell: 'dnf -y update'
    - name: install all appliations at webserver
      dnf:
       name: nginx
       state: present
      when: inventory_hostname in groups['webserver']
    - name: install all application for appserver
      dnf:
       name: "{{item}}"
       state: present
      loop:
       - nginx
       - php
      when: inventory_hostname in groups['appserver']
    - name: install all softwares for dbserver
      dnf:
       name: "{{item}}"
       state: present
      loop:
        - mariadb105-server
        -
      when: inventory_hostname in groups['dbserver']




    - name: start all appliations at webserver
      service:
       name: nginx
       state: started
      when: inventory_hostname in groups['webserver']



    - name: start all application for appserver
      service:
       name: "{{item}}"
       state: started
      loop:
       - nginx
       - php-fpm
      when: inventory_hostname in groups['appserver']


    - name: start all softwares for dbserver
      service:
       name: mariadb
       state: started
      when: inventory_hostname in groups['dbserver']
