- name: secret
  hosts: localhost
  become: yes
  connection: local

  vars_files:
    - mypass.txt

  tasks:
    - name: Update apt packages
      apt:
        name: '*'
        state: latest
        update_cache: yes

    - name: Install pip
      apt:
        name: python3-pip
        state: present

    - name: Install Python MySQL module
      apt:
        name: python3-pymysql
        state: present

    - name: Install MySQL server
      apt:
        name: mysql-server
        state: present

    - name: Start MySQL service
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Create MySQL user
      community.mysql.mysql_user:
        name: "{{ username }}"
        password: "{{ password }}"
        login_unix_socket: /var/run/mysqld/mysqld.sock
        check_implicit_admin: yes
        state: present
        update_password: always
